### ISSUE TITLE
Physics Model

### ISSUE THREAD

**Issue by dasaldino1** [Team8727/2023_Robot_Code#31]

**Comment by graham8727** [comment]
Can you explain more what the physics model needs to take into account?

**Comment by graham8727** [comment]
The arm its fixed to the robot, right?

**Comment by dasaldino1** [comment]
> The arm its fixed to the robot, right?

https://docs.wpilib.org/en/stable/docs/software/advanced-controls/state-space/state-space-intro.html
https://file.tavsys.net/control/controls-engineering-in-frc.pdf
http://underactuated.mit.edu/multibody.html
